#!/usr/bin/env bash
#Builds shaders.hpp, the hardware renderer's shaders as the program carries them, from the GLSL beside this script
#(docs/psp-gpu-renderers.md, "Shaders"): SPIR-V for Vulkan from glslang, and the GLSL itself for OpenGL. The
#fragment shader is built twice: with dual-source blending's second output, and without (SINGLE), for GPUs that
#lack it; copy.vert, copy.frag and present.frag are upscaling's and the screen's; transform.vert is fast mode's;
#move.frag moves pixels from one target into another.
#shaders.hpp is kept in the repository, so that building Phobos needs no shader compiler; it records the sources'
#SHA-256, which --check compares with the sources as they are (tests/psp/run-tests.sh runs it), and with
#glslangValidator there too, --check compiles them again and compares the result with shaders.hpp byte for byte.
#usage: compile.sh            (needs glslangValidator: Homebrew's or the Vulkan SDK's glslang)
#       compile.sh --check
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
OUT=$HERE/shaders.hpp
ALL="draw.vert draw.frag copy.vert copy.frag present.frag transform.vert move.frag compile.sh"

sha256() {
  if command -v sha256sum > /dev/null; then sha256sum | cut -d' ' -f1; else shasum -a 256 | cut -d' ' -f1; fi
}
hash=$(cd "$HERE" && cat $ALL | sha256)

work=$(mktemp -d "${TMPDIR:-/tmp}/psp-shaders.XXXXXX")
trap 'rm -rf "$work"' EXIT

compileAll() {
  { echo '#version 450'; cat "$HERE/draw.vert"; } > "$work/draw.vert"
  { echo '#version 450'; cat "$HERE/draw.frag"; } > "$work/draw.frag"
  { echo '#version 450'; echo '#define SINGLE'; cat "$HERE/draw.frag"; } > "$work/single.frag"
  for stage in copy.vert copy.frag present.frag transform.vert move.frag; do
    { echo '#version 450'; cat "$HERE/$stage"; } > "$work/$stage"
  done
  for stage in draw.vert draw.frag single.frag copy.vert copy.frag present.frag transform.vert move.frag; do
    glslangValidator -V --target-env vulkan1.0 -o "$work/$stage.spv" "$work/$stage" > "$work/log" 2>&1 ||
      { cat "$work/log"; exit 1; }
  done
}

words() {
  od -An -v -tx4 "$1" | awk '{ line = " "; for(i = 1; i <= NF; i++) line = line " 0x" $i ","; print line }'
}

header() {
  echo "//Generated by compile.sh from the GLSL beside it (docs/psp-gpu-renderers.md, \"Shaders\"): don't edit; run"
  echo "//compile.sh after changing the GLSL."
  echo "#pragma once"
  echo
  echo "namespace ares::PlayStationPortable::GPUShaders {"
  echo
  echo "static constexpr char SourceHash[] = \"$hash\";"
  echo
  echo "static const u32 vertexSPIRV[] = {"; words "$work/draw.vert.spv"; echo "};"
  echo
  echo "static const u32 fragmentSPIRV[] = {"; words "$work/draw.frag.spv"; echo "};"
  echo
  echo "static const u32 fragmentSingleSPIRV[] = {"; words "$work/single.frag.spv"; echo "};"
  echo
  echo "static const u32 copyVertexSPIRV[] = {"; words "$work/copy.vert.spv"; echo "};"
  echo
  echo "static const u32 copyFragmentSPIRV[] = {"; words "$work/copy.frag.spv"; echo "};"
  echo
  echo "static const u32 presentSPIRV[] = {"; words "$work/present.frag.spv"; echo "};"
  echo
  echo "static const u32 transformSPIRV[] = {"; words "$work/transform.vert.spv"; echo "};"
  echo
  echo "static const u32 moveSPIRV[] = {"; words "$work/move.frag.spv"; echo "};"
  echo
  echo "}"
}

if [[ ${1:-} == --check ]]; then
  recorded=$(sed -n 's/^static constexpr char SourceHash\[\] = "\([0-9a-f]*\)";$/\1/p' "$OUT")
  if [[ $recorded != "$hash" ]]; then
    echo "ares/psp/ge/gpu/shaders/shaders.hpp is out of date with its GLSL: run ares/psp/ge/gpu/shaders/compile.sh"
    exit 1
  fi
  if command -v glslangValidator > /dev/null; then
    compileAll
    header > "$work/shaders.hpp"
    if ! cmp -s "$work/shaders.hpp" "$OUT"; then
      echo "ares/psp/ge/gpu/shaders/shaders.hpp isn't what its GLSL compiles to: run ares/psp/ge/gpu/shaders/compile.sh"
      exit 1
    fi
  fi
  exit 0
fi

command -v glslangValidator > /dev/null || { echo "compile.sh needs glslangValidator (glslang)"; exit 1; }
compileAll
header > "$OUT"
echo "wrote $OUT"
