#!/usr/bin/env bash
#Builds shaders.hpp, the GPU renderer's compute shaders as the program carries them, from the GLSL beside this
#script (docs/psp-gpu-renderers.md, "Shaders"): for Vulkan, SPIR-V from glslang; for OpenGL (ES 3.2, or desktop
#4.3), the very same GLSL as text, which the driver compiles. Each stage is one source made of the shared files and
#its own, in the order below, after its backend's prelude. shaders.hpp is kept in the repository, so that building
#Phobos needs no shader compiler; it records the sources' SHA-256, which --check compares with the sources as they
#are (no compiler needed: tests/psp/run-tests.sh runs it), so a change to the GLSL without running this fails. With
#glslangValidator there too, --check compiles the GLSL again and compares what comes out with shaders.hpp, byte for
#byte (glslang's output is the same from one run to the next), so an edit to the SPIR-V by hand fails as well.
#usage: compile.sh            (needs glslangValidator: Homebrew's or the Vulkan SDK's glslang)
#       compile.sh --check    (the recorded hash against the sources; with glslangValidator, shaders.hpp too)
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
OUT=$HERE/shaders.hpp
STAGES="bin raster probe"
sources() {  #the files of a stage, in order
  case $1 in
  bin) echo "common.glsl exact.glsl bin.comp" ;;
  raster) echo "common.glsl exact.glsl texture.glsl pixel.glsl raster.comp" ;;
  probe) echo "common.glsl exact.glsl texture.glsl probe.comp" ;;
  esac
}
ALL="common.glsl exact.glsl texture.glsl pixel.glsl bin.comp raster.comp probe.comp compile.sh"

sha256() {
  if command -v sha256sum > /dev/null; then sha256sum | cut -d' ' -f1; else shasum -a 256 | cut -d' ' -f1; fi
}
hash=$(cd "$HERE" && cat $ALL | sha256)

#The backends' preludes: how each names bindings and constants. OpenGL's #version and constants are the program's
#to put first (the GL backend), as the constants' values are only known then: here, the defaults.
vulkanPrelude() {
  printf '%s\n' '#version 450' \
    '#define BUFFER(n) layout(set = 0, binding = n, std430)' \
    '#define UNIFORMS(n) layout(set = 0, binding = n, std140)' \
    '#define CONSTANT(id, name, macro, value) layout(constant_id = id) const uint name = value;'
}
glPrelude() {
  printf '%s\n' 'precision highp float;' 'precision highp int;' \
    '#define BUFFER(n) layout(binding = n, std430)' \
    '#define UNIFORMS(n) layout(binding = n, std140)' \
    '#define CONSTANT(id, name, macro, value) const uint name = macro;'
}
stageSource() {  #a stage's GLSL after a prelude
  local file
  for file in $(sources "$1"); do cat "$HERE/$file"; done
}

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

#The GLSL compiled (for Vulkan) or checked (as OpenGL ES 3.20's and desktop OpenGL 4.30's compute shaders).
compileAll() {
  local stage
  for stage in $STAGES; do
    { vulkanPrelude; stageSource "$stage"; } > "$work/$stage.comp"
    glslangValidator -V --target-env vulkan1.0 -o "$work/$stage.spv" "$work/$stage.comp" > "$work/log" 2>&1 ||
      { cat "$work/log"; exit 1; }
    for version in '320 es' '430'; do
      { echo "#version $version"; echo '#define FUSED 1u'; echo '#define NATIVE_FMA 1u'; glPrelude
        stageSource "$stage"; } > "$work/$stage-gl.comp"
      glslangValidator -S comp "$work/$stage-gl.comp" > "$work/log" 2>&1 ||
        { echo "$stage as OpenGL $version's:"; cat "$work/log"; exit 1; }
    done
  done
}

#shaders.hpp, from what compileAll() made
header() {
  local stage
  echo "//Generated by compile.sh from the GLSL beside it (docs/psp-gpu-renderers.md, \"Shaders\"): don't edit; run"
  echo "//compile.sh after changing the GLSL. SPIR-V for Vulkan; the GLSL itself for OpenGL, which comes after the"
  echo "//program's own #version and its #defines of FUSED and NATIVE_FMA (the constants fused and nativeFma)."
  echo "#pragma once"
  echo
  echo "namespace ares::PlayStationPortable::GPUShaders {"
  echo
  echo "static constexpr char SourceHash[] = \"$hash\";"
  for stage in $STAGES; do
    echo
    echo "static const u32 ${stage}SPIRV[] = {"
    od -An -v -tx4 "$work/$stage.spv" |
      awk '{ line = " "; for(i = 1; i <= NF; i++) line = line " 0x" $i ","; print line }'
    echo "};"
  done
  for stage in $STAGES; do
    echo
    echo "static const char ${stage}GLSL[] = R\"glsl("
    glPrelude
    stageSource "$stage"
    echo ")glsl\";"
  done
  echo
  echo "}"
}

if [[ ${1:-} == --check ]]; then
  recorded=$(sed -n 's/^static constexpr char SourceHash\[\] = "\([0-9a-f]*\)";$/\1/p' "$OUT")
  if [[ $recorded != "$hash" ]]; then
    echo "ares/psp/ge/gpu/shaders/shaders.hpp is out of date with its GLSL: run ares/psp/ge/gpu/shaders/compile.sh"
    exit 1
  fi
  if command -v glslangValidator > /dev/null; then
    compileAll
    header > "$work/shaders.hpp"
    if ! cmp -s "$work/shaders.hpp" "$OUT"; then
      echo "ares/psp/ge/gpu/shaders/shaders.hpp isn't what its GLSL compiles to (edited by hand, or another"
      echo "glslang's): run ares/psp/ge/gpu/shaders/compile.sh"
      exit 1
    fi
  fi
  exit 0
fi

command -v glslangValidator > /dev/null || { echo "compile.sh needs glslangValidator (glslang)"; exit 1; }
compileAll
header > "$OUT"
echo "wrote $OUT"
